name: smartsnapper
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  geodesy: ^0.10.2
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.2.16
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectfill
  color: "#000000"

flutter: 
  uses-material-design: true
  assets:
    - assets/images/


